# Parameters for Octomap

# Fixed frame for the map to exist in.
frame_id: world

# Leaf voxel size.
resolution: 0.5

# Sensor model.
sensor_model:
  min_range: 1.0
  max_range: 25.0

  # Log-odds grid cell probability update for hits and misses.
  miss: 0.4
  hit: 0.7

  # Occupancy clamping thresholds.
  min: 0.12
  max: 0.97

# Max depth.
max_depth: 16

# Remove noise in the map from sensor noise.
filter_speckles: false

# Prune tree when laser scans are inserted.
compress_map: false