icp:
  # RANSAC threshold for ICP.
  ransac_thresh: 15.0

  # Stop ICP after difference in transformation is small enough.
  tf_epsilon: 0.00000001

  # Correspondence threshold.
  corr_dist: 15.0

  # Max number of ICP iterations.
  max_iters: 10